### ISSUE TITLE
error while trying to build and push Docker image

### ISSUE THREAD

**Issue by icrtiou** [GoogleCloudPlatform/kubernetes-bigquery-python#11]
while doing `sudo docker build -t gcr.io/<project_id>/pubsub_pipeline $EXAMPLE_DIR/pubsub/pubsub-pipe-image ` (I did change to my project name)

Terminal gives me these:
>  Post http:///var/run/docker.sock/v1.20/build?cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&memory=0&memswap=0&rm=1&t=gcr.io%2Fluka-twitter%2Fpubsub_pipeline&ulimits=null: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?

I am using:
> mac osx 10.10
>  docker  Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64

Any idea? Thanks

**Comment by jeffmendoza** [comment]
`docker build` is running the docker client, which needs to talk to a docker daemon that you are running somewhere. Docker only runs on Linux, so for Mac you'll need to run it in a VM on your machine. The established tool for this is [boo2docker](http://boot2docker.io/), but that is being replaced by Docker machine, which is a part of the new [Docker Toolbox.](https://www.docker.com/toolbox)

**Comment by icrtiou** [comment]
Ok, I got the linux machine running no problem. Thx
