### ISSUE TITLE
Request had insufficient authentication scopes

### ISSUE THREAD

**Issue by dankasak** [GoogleCloudPlatform/kubernetes-bigquery-python#15]
I've followed both these instructions, and the ones at https://cloud.google.com/solutions/real-time/kubernetes-pubsub-bigquery ( dropping and re-creating all VMs in between ), and I'm getting "Request had insufficient authentication scopes" using both methods.

Full error:

---

{
 metadata: {
  severity: "INFO"    
  projectId: "viator-dimension"    
  serviceName: "container.googleapis.com"    
  zone: "us-central1-b"    
  labels: {…}    
  timestamp: "2016-11-15T01:41:37Z"    
 }
 textPayload: "Exception: <HttpError 403 when requesting https://pubsub.googleapis.com/v1beta2/projects/viator-dimension/subscriptions/tweets-twitter:pull?alt=json returned "Request had insufficient authentication scopes.">
"   
 insertId: "1kvsa6mfw0b40a"   
 log: "bigquery"   
}

---

When examining the VM instances, I've noticed that none of them have access to the BigQuery or PubSub APIs. Further, the documentation relating to this area appears out of date. The docs here state:

1) Edit kubernetes/cluster/gce/config-default.sh.
2) Add the bigquery and https://www.googleapis.com/auth/pubsub scopes to the file's NODE_SCOPES definition.

 ... but adding these values and starting the cluster brings up VMs *without* access to these APIs.

What's missing?

**Comment by jeffmendoza** [comment]
Hmm, just looked into this, looks like this commit https://github.com/kubernetes/kubernetes/commit/3f5fbee19dcdd0c7f2c64f0058ae18023b2d4685 https://github.com/kubernetes/kubernetes/pull/27466 moved the scopes setting to cluster/gce/config-common.sh but did not remove them from config-default.

@amygdala is there a reason this solution does not use Container Engine?

**Comment by amygdala** [comment]
@jeffmendoza Originally there were some reasons, but I think they have been mostly obviated at this point.  (One thing that still may be relevant is a redis-related sysctl setting for better performance).
Probably we should move the example to use Container Engine now. 
But, I'll fix the config instructions to start with.

**Comment by amygdala** [comment]
Dan, the readme for the pubsub version (https://github.com/GoogleCloudPlatform/kubernetes-bigquery-python/blob/master/pubsub/README.md) has now been updated with the correct config instructions.  The instructions in the corresponding google docs articles have yet to be updated, but they will be soon.  
I also fixed an ingestion issue related to a change to the twitter schema.

**Comment by jeffmendoza** [comment]
Closed with #21 switch instructions to GKE
