### ISSUE TITLE
Deprecate this repo?

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/kubernetes-bigquery-python#25]
@amygdala I see that the solutions team dropped the article where this code was used. See b/110952182 Time to archive this repo?

**Comment by amygdala** [comment]
@tswast Sorry about the slow response.
This repo code, and the readmes, are more up to date than the 'solutions'.  AFAIK what's here works fine.  We should keep this if it's useful/interesting. (I think it is).
Ryan and I just didn't manage to coordinate in a timely fashion on the cloudsite updates...
