### ISSUE TITLE
Update the apiVersion for Deployment and add Selectors to Spec

### ISSUE THREAD

**Issue by saurabh-slacklife** [GoogleCloudPlatform/kubernetes-bigquery-python#29]
Since K8s release version 1.16, the extensions: **extensions/v1beta1**, **apps/v1beta1**, and **apps/v1beta2** were retired. Hence the below manifests needs to be updated accordingly.

- [pubsub/bigquery-controller.yaml](https://github.com/GoogleCloudPlatform/kubernetes-bigquery-python/blob/master/pubsub/bigquery-controller.yaml)
- [pubsub/twitter-stream.yaml](https://github.com/GoogleCloudPlatform/kubernetes-bigquery-python/blob/master/pubsub/twitter-stream.yaml)
- [redis/bigquery-controller.yaml](https://github.com/GoogleCloudPlatform/kubernetes-bigquery-python/blob/master/redis/bigquery-controller.yaml)
- [redis/redis-master.yaml](https://github.com/GoogleCloudPlatform/kubernetes-bigquery-python/blob/master/redis/redis-master.yaml)
- [redis/twitter-stream.yaml](https://github.com/GoogleCloudPlatform/kubernetes-bigquery-python/blob/master/redis/twitter-stream.yaml)

**Comment by saurabh-slacklife** [comment]
Also I can take this up and submit a PR.

- S
Thanks!

**Comment by saurabh-slacklife** [comment]
#30

**Comment by saurabh-slacklife** [comment]
@Daniel-Sanche @tswast Since #30 is now merged with master, can we assign and hence close this issue?

**Comment by tswast** [comment]
Yes.

Thanks for the contribution, @saurabh-slacklife !
